### ISSUE TITLE
Add Instagram recipe/service

### ISSUE THREAD

**Issue by ZeroCool940711** [getferdi/recipes#1]
Would be nice to have a Ferdi recipe/service for Instagram Direct Messages, that way we could use ferdi for Instagram on desktop instead of another app. 

I've found [this](https://github.com/alexdevero/franz-instagram-recipe) repository with a franz recipe but it seems to be outdated and the chat is broken. 

First of all when you write a text and hit `Enter` on the keyword it has a behavior like pressing `Enter+Shift`, it do not send the message but instead move the cursor to a new line, so the only way to send the message is clicking on the Send button which is annoying. 

Also the text is too small and the box around the text wraps like three-five words per line making long text use a lot of space and be hard to read but also make it that each message uses only a small part of the window horizontal space. Meaning it creates a long vertical message but small horizontally, doesn't even reach the middle of the chat window. It would make it easier to read and I think lot of people would appreciate this recipe/service. 

Unfortunately I dont know what to fix so it works, probably someone else can do it, here is a screenshot of the behavior I mentioned before, I removed the text and usernames on the image but I think it will help to illustrate what I mean.
![Untitled](https://user-images.githubusercontent.com/5977640/65537262-c2cc5d80-deb9-11e9-936c-d5f242c00582.jpg)

**Comment by marcorichetta** [comment]
Hi!

I followed the steps above and I have some doubts:
- First I used the UA from https://github.com/marnovo/franz-recipe-instagram/blob/master/index.js because it allows to use DMs
`"Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19";`

- Then I changed to an updated UA that allowed the same functionality
`'Mozilla/5.0 (Linux; Android 6.0.1; SM-G935T Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36';`

The problem I'm having is that in a 1366*768 maximized window on my laptop, the stories disappear. When I resize the window, by dragging up, the stories can be seen.
Edit: I just realized that stories can be seen up to 1000px horizontal.

Should we try to imitate Instagram's mobile functionality or should we go with the normal web browser functionality?
The repo is here: https://github.com/marcorichetta/franz-instagram-recipe

### Ferdi Info
Version: 5.4.0-beta.2 (x64)
Electron: 6.0.10
Node.js: v12.4.0
Platform: linux

**Comment by kytwb** [comment]
I think it's better to keep the service address to `https://www.instagram.com/direct/inbox/` so users gets directly redirected to the messaging service of Instagram after getting logged in and when coming again to their Instagram service.

Introduced custom CSS to deal with:

> Also the text is too small and the box around the text wraps like three-five words per line making long text use a lot of space and be hard to read but also make it that each message uses only a small part of the window horizontal space. Meaning it creates a long vertical message but small horizontally, doesn't even reach the middle of the chat window. It would make it easier to read and I think lot of people would appreciate this recipe/service.

Taking a look at:

> First of all when you write a text and hit Enter on the keyword it has a behavior like pressing Enter+Shift, it do not send the message but instead move the cursor to a new line, so the only way to send the message is clicking on the Send button which is annoying.

**Comment by kytwb** [comment]
I just noticed the CSS fix to deal with the text width is messing with the messages that are images. I will need to see if I can improve this. Also, the Enter+Shit is a change of behaviour. I think we can ship a working version of the Instagram recipe (with the notification badge working) and see to enhance the readability and comfort feature (Enter as send) later. WDYT?

**Comment by kytwb** [comment]
Publishing working version as it so it ships with the next Ferdi update. We can discuss/open new tickets for enhancement propositions as it seems they might take a bit more time to spec fully and implement.

**Comment by tamerciaga** [comment]
I'm re-opening this issue due to the following:

> First of all when you write a text and hit Enter on the keyword it has a behavior like pressing Enter+Shift, it do not send the message but instead move the cursor to a new line, so the only way to send the message is clicking on the Send button which is annoying.

Is there a way to enable the default Enter behaviour using recipes? I didn't find anything in the docs.

This is issue ID 1, how cool is that 🥇

**Comment by kytwb** [comment]
@tamerciaga an update will be brought to the Instagram recipe to use the new/official web version of direct messages, via https://github.com/getferdi/recipes/issues/59 🙏

**Comment by birobirobiro** [comment]
@kytwb Add this code in package.json in Instagram

```
"use strict";

module.exports = Franz =>
  class Messenger extends Franz {
    overrideUserAgent() {
      return window.navigator.userAgent.replace(
        /(Franz|Electron)([^\s]+\s)/g,
        ""
      );
    }
  };
```

![2020-03-09_12-45](https://user-images.githubusercontent.com/22185823/76231333-df5c1800-6203-11ea-99f9-c43b3255525e.png)

**Comment by tamerciaga** [comment]
@birobirobiro that doesn't seem to be working, I get the following error:
`Sorry, this page isn't available.`

**Comment by kytwb** [comment]
Oh ok, so maybe the new inbox isn't globally available. The current recipe still works for me in Ferdi; I can also go to https://www.instagram.com/direct/inbox/ in my browser now without changing my user agent (like Ferdi does with the recipe, to fake being on the previously-mobile-only web version, otherwise it would show

**Comment by kytwb** [comment]
Re-opened by mistake.

**Comment by birobirobiro** [comment]
> Oh ok, so maybe the new inbox isn't globally available. The current recipe still works for me in Ferdi; I can also go to https://www.instagram.com/direct/inbox/ in my browser now without changing my user agent (like Ferdi does with the recipe, to fake being on the previously-mobile-only web version, otherwise it would show `Sorry, this page isn't available.`

I live in Brazil, it may be that soon it will be available globally
