### ISSUE TITLE
Inoreader

### ISSUE THREAD

**Issue by MauricioAedo** [getferdi/recipes#192]
Inoreader: 
inoreader.com:

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by SkepticSpoon** [comment]
I also would like to have InoReader. I've found a recipe for Franz here: https://github.com/annagrram/recipe-inoreader

I've imported it to my local Ferdi install and it works, but without Unread count badge.

I don't know if this helps

**Comment by vraravam** [comment]
thanks for the heads up @SkepticSpoon . Would it be possible for you to log an issue ticket with the original recipe author - so that they can fix the unread count? Once done, I can import it into Ferdi.

(Sorry, since I dont use Inoreader, I am unable to sign up for it and test/make the fix). Thanks for understanding.
