### ISSUE TITLE
Unread count in Whatsapp not working

### ISSUE THREAD

**Issue by vraravam** [getferdi/recipes#370]
**Describe the bug**
Using the Whatsapp recipe, the unread count has stopped working.

**To Reproduce**
1. Add the Whatsapp recipe
2. Move to a different service in Ferdi
3. Get a message from a friend to your WA account - do not open/read in any device
4. See that the unread count for the WA service never shows up in Ferdi

**Expected behavior**
The service icon usually has a circular overlay that shows the unread count.

**Screenshots**
<img width="54" alt="Screenshot 2020-11-25 at 3 20 48 PM" src="https://user-images.githubusercontent.com/69629/100211169-d1852900-2f31-11eb-87bf-3db5fa25f625.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Ferdi
 - Version 5.6.0-nightly.11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bpwned** [comment]
I can confirm this also happens on 5.5.0 and Catalina.

**Comment by psimovec** [comment]
I can confirm too, 5.5.0 and Fedora 32
I was just writing an issue in the wrong place (getferdi/ferdi), and found out that this issue is already here.. so I'm just gonna paste it here. I have also created an ugly hackish fix, at most for personal use until the issue is fixed properly by someone else.


**Bug description:**

Whatsapp does not show the number of new messages on the Ferdi sidebar. (Sorry for not a proper bug report, I don't have much time, I hope it's sufficient)

**Steps to reproduce:**

_1. Have a friend
2. Convince the friend to install WhatsApp
3. Convince the friend to add you on WhatsApp
4. Convince the friend to message you on WhatsApp (do not open the message, just ignore the friend)_
**5. Look on the Ferdi sidebar, no number of new messages on WhatsApp displayed.**

**Environment:**
- Operating System: Fedora 32
- Ferdi Version: Version 5.5.0
- Server: default, no account

- Debug information:

I have changed the local webview.js of WhatsApp.
and I have fixed it sufficiently just for myself in a super ugly hackish way.  Just checking any divs that have span with any aria-label inside and then checking if innerText is integer :D Please don't crucify me for this :D  
(old code that was there is commented out)
**My guess is that the problem is in the following line:**
`const elements = document.querySelectorAll("[class=OUeyt]");`

This line on this repo, it has a different class name
https://github.com/getferdi/recipes/blob/c40fae916884a1754cec8d3ec28b5cdfc7e5370a/recipes/whatsapp/webview.js#L31

it seems that it tries to get class by name that is... I believe randomly generated, but I might be wrong.
**I don't have time to do a proper fix, so I wanted to try to give you a clue at least**.
```
module.exports = Franz => {
  const getMessages = function getMessages() {
    //const elements = document.querySelectorAll("[class=OUeyt]"); // <--- My guess is problem is that problem is here, I might be wrong
    var count = 0;
	var indirectCount = 0;
/*
    for (var i = 0; i < elements.length; i += 1) {
	  var countValue = parseInt(elements[i].textContent, 10);
	  
      if (elements[i].parentNode.previousElementSibling === null || elements[i].parentNode.previousElementSibling.querySelectorAll("[data-icon=muted]").length === 0) {
        count += countValue;
      } 
	  else {
		indirectCount += countValue;
	  }
    }*/



	  
	  result = document.evaluate("//div[./span[@aria-label]]",document); for ( i=0; i<10; i+=1 ){
          number = result.iterateNext()
	if (number === null){break;}
		number=number.innerText;
            original=number;
           number = parseInt(number);  
          if (number !=NaN && number < 6 && number==original){console.log(number, original);
                count += number;
          }       
	  }
	  if (count == NaN){
		count=69
	  }
	  indirectCount=count;
	  

    Franz.setBadge(count, indirectCount);
  };

  Franz.injectCSS(path.join(__dirname, 'service.css'));
  Franz.loop(getMessages);
};
```

**Comment by bpwned** [comment]
Thanks, but unfortunately this hack doesn't seem to work for me either. Oh well…

**Comment by vraravam** [comment]
latest version of the WA recipe seems to work - closing this issue
