### ISSUE TITLE
freshservice

### ISSUE THREAD

**Issue by alberttcg** [getferdi/recipes#43]
Name of the service (e.g. WhatsApp): Fresh Service
URL of the service (e.g. whatsapp.com): https://freshservice.com

GitHub URL to a recipe : 

Features you want implemented (optional):

-

**Comment by vantezzen** [comment]
Your issue has been marked as "no existing recipe". Normally, we add existing recipes from GitHub as those have already been tested and contain the most important features.
As this service doesn't have existing recipes on GitHub we can't add any. Please develop this recipe on your own - we will then add this to the repository - or link an existing recipe. Otherwise we'll have to close this issue due to low demand. In this case we advice you to add your service with the "Custom website" recipe.
