### ISSUE TITLE
Integration with Signal, a regular e-mail client, KMail, KAddress, Kontact<SERVICE>

### ISSUE THREAD

**Issue by gilunixuser** [getferdi/recipes#434]
Name of the service (e.g. WhatsApp): 
- Signal Messenger, 
- Kmail / Kontact / KAddressbook (KDE Linux)
URL of the service (e.g. whatsapp.com): 
https://signal.org/
https://apps.kde.org/en/kontact
https://kontact.kde.org/components/kmail.html
https://kontact.kde.org/components/kaddressbook.html

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):
An interface for sending messages 
a) via Signal 
b) through a regular and simple e-mail account.
c) via Kmail / Kontact (KDE Linux)
d) while using your own address book, e.g. KAddress which is a part of Kontact ( KDE Linux)

**Comment by vraravam** [comment]
@gilunixuser - since I do not use this service, it will be hard for me to implement the unread messages count, etc. Please use the code generator to create the basic shell and then implement any customizations (eg unread message counts/badges, etc).

Also, Signal uses proprietary encryption which is not available via a browser.

**Comment by JowJoris** [comment]
@gilunixuser Signal can't be added as explaned [here](https://help.getferdi.com/services/services)
