### ISSUE TITLE
signal, element 

### ISSUE THREAD

**Issue by eertan05** [getferdi/recipes#449]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@eertan05 - please separate your service requests - one per ticket.

btw: Signal has already been requested - and due to the absence of a web-based version, Ferdi will not be able to support it.

For element, its already present. Please upgrade to the latest nightlies from [here](https://github.com/vraravam/nightlies/releases) to get this service showing up in your local installation.
