### ISSUE TITLE
Hangouts Chat (ie new Google Chat) recipie does not display preview images anymore

### ISSUE THREAD

**Issue by wiggisser** [getferdi/recipes#472]
**Describe the bug**

The hangouts chat recipie does not display preview images sent via the Google Chat mobile app or the Google Chat webapp (ie the very same webapp this recipie is displaying) anymore. Instead a placeholder is shown. When you click on the placeholder an messagebox is shown that there was an error previewing the image and contaning a link to download the image. (see screenshots)

The same images are shown just fine in the mobile app and in the webapp in lastest Chrome ... 

Interestingly, images sent from the mobile Hangouts app are displayed just fine ... 

**To Reproduce**

1. Open ferdi
2. Switch to the Hangouts Chat service
3. Observe

**Expected behavior**

Should display preview images and nost just the placeholder

**Screenshots**

Only an image placeholder is displayed in ferdi

![image](https://user-images.githubusercontent.com/3647678/114720654-7e710e80-9d38-11eb-83a8-f02adc050e65.png)

When I click on the placeholder, a message box appears

![image](https://user-images.githubusercontent.com/3647678/114719686-a01dc600-9d37-11eb-9e9a-47ce8fd198af.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/3647678/114719317-3d2c2f00-9d37-11eb-8113-c14bd9194e11.png)

**Comment by Pawel-Dymek** [comment]
Same here

**Comment by themagpieswarble** [comment]
Same here. Any idea on a fix?

**Comment by vraravam** [comment]
Please see [here](https://github.com/getferdi/ferdi/issues/1283#issuecomment-827755875) for the fix

**Comment by mastercko** [comment]
I'm having the same problem in 5.6.0-nightly.48

Version information:
![image](https://user-images.githubusercontent.com/6900268/120092430-af24d000-c14d-11eb-86b2-5734c478af73.png)

The linked solution is not applicable, this is the full text of my current `recipes/hangoutschat/index.js` file:

```js
var os = require('os')

// just pass through Franz
module.exports = Franz =>
  class HangoutsChat extends Franz {
  };
```

**Comment by mastercko** [comment]
Interesting. I just did the following and it seemed to fix it?

1. In Ferdi, while looking at the Google Hangouts Chat service, select the "View" Menu
2. Select "Toggle Service Developer Tools" near the bottom
3. Select "Storage" in the "**Application**" section 
4. Select "Clear site data" button (you can include 3rd party cookies if you want, though not sure if it matters)
5. Close the Developer Tools window and completely quit Ferdi.
6. Relaunch Ferdi.
7. Re-sign-in to Google Chat.

And it seems that has fixed the issue? At least my past images are showing properly now. 

I guess it might be that the cache still had data in it from my previous version of Ferdi (nightly.15). Anyway, I'll keep an eye out on it and see what happens when new images come in.

**Comment by vraravam** [comment]
Yes - that could be the case. When Ferdi detects that there are newer versions of recipes, it will only update the recipes - but not touch the cache (we wouldn't want the user to get automatically logged out of their website!).

Old cache can cause unforeseen issues. Thanks for trying it out and detailing the steps here so that it might help others!
