### ISSUE TITLE
Google Podcasts missing?

### ISSUE THREAD

**Issue by zemmyang** [getferdi/recipes#488]
https://getferdi.com/services/ shows Google Podcasts as one of the available services for Ferdi, but when I try to add it, it says "not found."

**Desktop**
version 5.5 on Xubuntu 20.10

**Comment by vraravam** [comment]
Please upgrade to the latest version of Ferdi. I think there has been a revamp of the underlying code after Ferdi v5.5.x due to which the newer recipes don't work with 5.5 any more. 

Please try the betas/nightlies over [here](#https://github.com/getferdi/nighlies) - which are themselves some months old, or from [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv) - these are my personal builds, and I am not sure if the `deb` that I have uploaded works. Please confirm that as well if you do try it out!
