### ISSUE TITLE
Add Notion as a service

### ISSUE THREAD

**Issue by kdarsh17** [getferdi/recipes#521]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vraravam** [comment]
@kdarsh17 - Since this is a recipe request, please log a new one in the [recipes](https://github.com/getferdi/recipes/issues/new?assignees=&labels=recipe+request&template=recipe_request.md&title=%3CSERVICE%3E) repo. As prompted, please fill in all appropriate information.

If you would like to contribute a new recipe, please follow the [clear instructions](https://github.com/getferdi/recipes/blob/master/docs/integration.md) to create one and submit as a PR.
