### ISSUE TITLE
Old version of PulseSMS is being served by Ferdi

### ISSUE THREAD

**Issue by Serubin** [getferdi/recipes#68]
**Describe the bug**
The old version of ferdi is still serving version 1.0.0 of pulseSMS rather than the latest version 1.1.2.

**Comment by vantezzen** [comment]
Thank you for your report.

Is there anything we'll have to change to serve a newer pulseSMS version? Ferdi is simply showing "<https://pulsesms.app>" - do we need to use a different URL?

**Comment by Serubin** [comment]
I'm referring to the plugin version. It was updated last month, but I've not seen the updated plugin come through on any of my machines.

**Comment by vantezzen** [comment]
Oh, I'm sorry,I misunderstood you there.
What version of Ferdi are you on?

**Comment by Serubin** [comment]
All good - Version 5.4.3 (5.4.3.994)

**Comment by vantezzen** [comment]
Ferdi recipes get distributed via new Ferdi versions only - there is no server that recipes fetch from.

This is why the new pulseSMS recipe is only available in Ferdi 5.4.4-beta.2 and beta.3 - you'll have to enable beta versions in order to see the recipe update.
Otherwise the new recipe will ship with the next version of Ferdi (5.4.4) which may still take some time as there are still bugs fixes and features we'll implement first.
