### ISSUE TITLE
Skype notifications counter not working

### ISSUE THREAD

**Issue by karolkpl** [getferdi/recipes#763]
I have group notification with bunch of unread messages - I can see red badge under group name and "chats" tab inside Skype, but Ferdi shows no badge.

**Comment by mmalisz** [comment]
Hi @vraravam,
I've identified the issue.

The problem lies with the querySelector here: https://github.com/getferdi/recipes/blob/master/recipes/skype/webview.js#L8
This assumes that the user uses english in the recipe.

For example, in polish version the query should be `Czaty` - replacing it in the recipe seems to make the badges work.

However, it's more of a workaround than a real fix.

**Comment by vraravam** [comment]
Unfortunately, I dont use skype. We will appreciate one of the other users to contribute a fix that can work across languages
